apiVersion: apps/v1
kind: Deployment
metadata:
  name: osrm-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: osrm-frontend
  template:
    metadata:
      labels:
        app: osrm-frontend
    spec:
      containers:
        - name: osrm-sul
          image: filipeparreira/osrm-sul:frontv8
          ports:
            - containerPort: 9966
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: osrm-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: osrm-service
  template:
    metadata:
      labels:
        app: osrm-service
    spec:
      containers:
        - name: osrm-sul
          image: filipeparreira/osrm-sul:v1
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: osrm-frontend-service
spec:
  selector:
    app: osrm-frontend
  ports:
    - protocol: TCP
      port: 9966
      targetPort: 9966
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: osrm-service
spec:
  selector:
    app: osrm-service
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
